backend:
  name: git-gateway
  branch: main

media_folder: "images/gallery"
public_folder: "/images/gallery"

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - name: "gallery"
        label: "Gallery Photos"
        file: "content/gallery.json"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            summary: "{{fields.caption}}"
            fields:
              - { label: "Photo", name: "image", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string", required: false }
